TOP_STONKS = ["aal", "aapl", "abbv", "abt", "acb", "aes", "afl", "agnc", "aiki", "am", "amat", "amc", "amd", "apa",
              "apha", "ar", "arkk", "atus", "auy", "axta", "azn", "ba", "baba", "bac", "bb", "bbd", "bcrx", "be",
              "bidu", "bkr", "bldp", "bmy", "bngo", "box", "bp", "brk.b", "bsx", "cciv", "ccl", "chgg",
              "clf", "clov", "cmcsa", "cog", "cop", "coty", "crm", "csco", "ctxr", "cvs", "cvx", "dal", "dbx",
              "ddog", "dis", "disca", "dkng", "dnn", "duk", "dvn", "ebay", "ebon", "eem", "efa", "eqt", "ewz",
              "fb", "fcel", "fcx", "fe", "fisv", "fitb", "fold", "fsly", "fti", "gdx", "ge", "gevo", "gild", "gld",
              "gm", "gme", "gold", "hal", "hban", "hepa", "hpe", "hpq", "hst", "hyg", "ibm", "ibn", "idex", "infy",
              "ino", "intc", "iq", "isbc", "itub", "iwm", "jblu", "jci", "jd", "jnj", "jpm", "kgc", "khc", "kmi",
              "ko", "kr", "labd", "li", "lkco", "lqd", "lumn", "luv", "lvs", "lyft", "mara", "mdlz", "mdt",
              "mgm", "mos", "mpc", "mrk", "mro", "mrvl", "ms", "msft", "mu", "nclh", "nee", "nem", "nio", "nke", "nly",
              "nndm", "nok", "nvda", "nvta", "nxtd", "on", "ontx", "orcl", "oxy", "pbr", "pep", "pfe", "pg", "pins",
              "pk", "pltr", "plug", "pm", "pton", "pypl", "qcom", "qqq", "qs", "rcl", "rf", "riot", "roku", "rrc",
              "rtx", "sabr", "schw", "se", "sens", "siri", "slb", "slv", "snap", "sndl", "so", "sos", "spwr",
              "spy", "sq", "sqqq", "srne", "su", "swn", "syf", "teva", "tfc", "tjx", "tlry", "tlt", "tmus", "tqqq",
              "trch", "trip", "tsla", "tsm", "twlo", "twtr", "ual", "uber", "usb", "uvxy", "vale", "vg", "viac",
              "vlo", "vxx", "vz", "wba", "wdc", "wfc", "wmb", "wmt", "xlb", "xle", "xlf", "xli", "xlp", "xlu",
              "xom", "xpev", "znga", "rkt", "uwmc", "skt"]
