use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :trader, TraderWeb.Endpoint,
  url: [host: "trader.tendies.ai", port: 80],
  http: [port: 80, protocol_options: [idle_timeout: 5_000_000, request_timeout: 5_000_000]],
  debug_errors: false,
  code_reloader: false,
  check_origin: false

# For now, do print debug messages in production
config :logger, level: :debug


config :trader, Trader.Repo,
  username: "trader_prod",
  password: System.get_env("DB_PASSWORD"),
  database: "trader_prod",
  hostname: "db",
  show_sensitive_data_on_connection_error: false,
  pool_size: 20,
  timeout: 600_000
